const characters=[
{name:"Verity",score:98.7,aura:100,lore:99,threat:96,type:"THE ORIGINAL",color:"yellow",desc:"The face of the entire universe. Friendly on the surface, but the deeper you go, the less trustworthy that smile becomes."},
{name:"Cruelity",score:97.4,aura:99,lore:94,threat:100,type:"THE MENACE",color:"red",desc:"One of the darker names associated with the Verity universe. Cruelity has absolutely no shortage of intimidation."},
{name:"Falsity",score:95.9,aura:97,lore:96,threat:94,type:"THE LIAR",color:"purple",desc:"Everything about Falsity raises questions. The name alone tells you that trusting this one probably isn't a great idea."},
{name:"Lovity",score:94.8,aura:95,lore:91,threat:76,type:"THE PROTECTOR",color:"pink",desc:"A much friendlier presence than most of the cast. Lovity is associated with protecting players rather than hunting them."},
{name:"Acuity",score:91.6,aura:89,lore:87,threat:70,type:"THE LITTLE COUSIN",color:"cyan",desc:"A smaller member of the Verity universe. Acuity brings a different personality to the increasingly strange cast."},
{name:"Manipulity",score:90.8,aura:93,lore:83,threat:97,type:"THE MANIPULATOR",color:"violet",desc:"An aggressive variant known for its levitation abilities. Definitely not the character you want following you around."},
{name:"Corruption",score:89.9,aura:96,lore:79,threat:98,type:"THE RIVAL",color:"black",desc:"A hostile presence that has been portrayed as a rival to Lovity. Pure bad-news energy."},
{name:"Deprity",score:86.5,aura:88,lore:81,threat:73,type:"THE BROKEN ONE",color:"gray",desc:"A stranger variation of Verity built around the idea of a character that has seen far too much."},
{name:"Sincery",score:84.7,aura:82,lore:78,threat:69,type:"THE VARIANT",color:"blue",desc:"One of the many community-made variations surrounding the growing Verity universe."},
{name:"Obscurity",score:82.3,aura:91,lore:85,threat:61,type:"THE WATCHER",color:"dark",desc:"A more mysterious Verity model with a calmer personality. Obscurity is associated with watching and helping rather than pure aggression."}
];

const $=id=>document.getElementById(id);
const rankingList=$("rankingList"),search=$("search"),sort=$("sort"),modal=$("modal");
function ranked(){let q=search.value.toLowerCase().trim(),a=characters.filter(c=>c.name.toLowerCase().includes(q)||c.type.toLowerCase().includes(q));if(sort.value!=="rank")a.sort((x,y)=>y[sort.value]-x[sort.value]);return a}
function render(){rankingList.innerHTML="";let a=ranked();if(!a.length){rankingList.innerHTML='<div class="empty-state">No characters found.</div>';return}a.forEach((c,i)=>{let e=document.createElement("article");e.className="ranking-card";e.innerHTML=`<div class="rank-number">#${i+1}</div><div class="character-avatar ${c.color}">${c.name[0]}</div><div class="character-info"><div class="character-type">${c.type}</div><h3>${c.name}</h3><p>${c.desc}</p></div><div class="mini-stats"><span>AURA <b>${c.aura}</b></span><span>LORE <b>${c.lore}</b></span><span>THREAT <b>${c.threat}</b></span></div><div class="character-score"><strong>${c.score}</strong><small>/100</small></div>`;e.onclick=()=>profile(c);rankingList.appendChild(e)})}
function profile(c){$("modalName").textContent=c.name.toUpperCase();$("modalScore").textContent=c.score;$("modalDesc").textContent=c.desc;$("modalStats").innerHTML=`<div><span>AURA</span><strong>${c.aura}</strong></div><div><span>LORE</span><strong>${c.lore}</strong></div><div><span>THREAT</span><strong>${c.threat}</strong></div>`;modal.classList.add("open");modal.setAttribute("aria-hidden","false")}
function close(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true")}
function random(){profile(characters[Math.floor(Math.random()*characters.length)])}
function duel(){let a=characters[Math.floor(Math.random()*characters.length)],b=a;while(b.name===a.name)b=characters[Math.floor(Math.random()*characters.length)];let w=a.score>=b.score?a:b;$("modalName").textContent=`${a.name} VS ${b.name}`;$("modalScore").textContent=w.name;$("modalDesc").textContent=`${w.name} wins the matchup based on the current editorial scores.`;$("modalStats").innerHTML=`<div><span>${a.name}</span><strong>${a.score}</strong></div><div><span>${b.name}</span><strong>${b.score}</strong></div><div><span>WINNER</span><strong>${w.name}</strong></div>`;modal.classList.add("open");modal.setAttribute("aria-hidden","false")}
$("count").textContent=characters.length;$("topAura").textContent=[...characters].sort((a,b)=>b.aura-a.aura)[0].name;$("topLore").textContent=[...characters].sort((a,b)=>b.lore-a.lore)[0].name;$("avgScore").textContent=(characters.reduce((s,c)=>s+c.score,0)/characters.length).toFixed(1);
$("randomBtn").onclick=random;$("duelBtn").onclick=duel;$("duelBtn2").onclick=duel;search.oninput=render;sort.onchange=render;$("closeModal").onclick=close;$("closeX").onclick=close;document.onkeydown=e=>{if(e.key==="Escape")close()};render();